general:
  branches:
    only:
      - master
      - develop

dependencies:
  pre:
    - chmod -R 777 ./example
    - pip install -r ./requirements.txt

test:
  override:
    - pwd ~
    - ifconfig
    - exit 0
