general:
  branches:
    only:
      - master
      - develop
 deployment:
  staging:
    branch: develop
  production:
    branch: master
 test:
    override:
      - echo "----- No executable test ----
